#!/usr/bin/env python
import configparser
import os
import git
from subprocess import check_output
from git import Repo


config = configparser.ConfigParser()
config.read('config_script/config.ini')
PERC_COMM_MIN = config['Comments_Counter']['Percentuale_Min_Comm']


def _cut_useles(files):
    """
    Cut the useles part of a raw and take only the file to commit
    :param files: list of files to commit or not
    :return file_list: list with only file to commit
    """
    files_list = []
    files = files.split('\n')
    for i in range(len(files)):
        if not files[i].startswith('?') and not files[i].startswith(' ') and \
           files[i].endswith('.py'):
            files[i] = files[i][2:]
            files[i] = files[i].strip(' ')
            files_list.append(files[i])
    return files_list


dir_path = os.path.abspath(os.curdir)
repo = Repo(dir_path)
git = repo.git
status = git.status('-s')
status = _cut_useles(status)
program_path = os.path.join(dir_path, "Git_Hooks", "Main.py")
for i in range(len(status)):
    file = os.path.join(dir_path, status[i])
    perc = check_output(['python', program_path, file])
    perc = perc.decode()
    perc = perc.split('\r')
    if perc[0] == 'pydoc assente':
        print("Nel file: " + status[i] + " pydoc mancanti o non sempre presenti")
        exit(1)
    if float(perc[0]) < PERC_COMM_MIN:
        print("Nel file: " + status[i] + " i commenti sono meno del 30%")
        print('Percentuale commenti: ' + perc[0])
        exit(1)
    else:
        print('Nel file: ' + status[i] + ' hai commentato bene, bravo')
        print('Percentuale commenti: ' + perc[0] + '%')
exit(0)
